stages:
  - test
  - deploy

test:
  image: node:8-alpine
  stage: test
  before_script:
    - npm install
  script:
    - npm test
  cache:
    paths:
      - node_modules/

deploy:
  image: docker:latest
  only: [master]
  services:
    - docker:dind
  stage: deploy
  script:
    - apk add --no-cache curl python
    - sh ./aws_login.sh
    - docker build -t $CI_PROJECT_NAME .
    - docker tag $CI_PROJECT_NAME:latest $AWS_REPO_NAME:latest
    - docker push $AWS_REPO_NAME:latest
